version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ly1y6iMtYf
      MINIO_ROOT_PASSWORD: VNcmMuDARGGstqzkXF1Van1Mlki5HGU9
    ports:
      - '9000:9000'
      - '32765:32765'
    volumes:
      - minio-data:/data
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:32765 /tmp

volumes:
  minio-data:
